export const gameOverPage = 'GameOver';
export const gamePage = 'Game';
export const homePage = 'Home';
export const playPage = 'Play';
export const authorizationPage = 'Authorization';
export const tutorialPage = 'Tutorial';
export const nextLevelPage = 'Level';
export const winnersPage = 'Winners';
export const cabinetPage = 'Cabinet';
export const RIGHT = 'RIGHT';
export const LEFT = 'LEFT';
export const UP = 'UP';
export const DOWN = 'DOWN';
export const pageNavArr = ['Home', 'Tutorial', 'Winners'];
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const CHANGE_LEVEL_POINTS = 'CHANGE_LEVEL_POINTS';
export const CHANGE_GAME_POINTS = 'CHANGE_GAME_POINTS';
export const CHANGE_LEVEL = 'CHANGE_LEVEL';