export const finishPage = 'Finish'
export const gamePage = 'Game'
export const homePage = 'Home'
export const playPage = 'Play'
export const authorizationPage = 'Authorization'
export const tutorialPage = 'Tutorial'
export const winnersPage = 'Winners'